version: '3.8'

services:
  prod:
    container_name: discordBot.hoursManager
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/tiagohasuda/projects/HoursManagerDiscordBot:/projects/discordBots/hoursManager
